### ISSUE TITLE
Does this code use momentum?

### ISSUE THREAD

**Issue by christiancosgrove** [cihangxie/DI-2-FGSM#2]
In 
https://github.com/cihangxie/DI-2-FGSM/blob/dfa64f2842561518f99515ea9572b42f9bee0c62/attack.py#L179

the variable `grad` is initialized to zero. Presumably, `grad` stores the accumulated gradient for momentum updates. However, it seems that `grad` is not updated anywhere else in the code. Am I missing something? 

Thanks!

**Comment by cihangxie** [comment]
There is a flag for momentum

tf.flags.DEFINE_float(
    'momentum', 0.0, 'Momentum.')
