### ISSUE TITLE
Return value of input_diversity function

### ISSUE THREAD

**Issue by lin2020** [cihangxie/DI-2-FGSM#3]
The return value of input_diversity function may be 'input_tensor' or 'padded'，but the shape of ‘input_tensor’ is [batch_size,299,299,3] and the shape of 'padded' is [batch_size, 331, 331, 3]. The code sometimes gets wrong, why not reshape 'padded' to [batch_size, 299, 299, 3]?

**Comment by cihangxie** [comment]
Could you please specify when the code will get wrong?

This transformation is done on the whole batch (i.e., all the batch will have the same shape), so I think it is okay to set the shape of the whole batch to be either 299 x 299 or 331 x 331? 

If you set the padded shape to be 299 (e.g., resize image between [256, 299] and then pad to 299), it is also okay. You will get similar (slightly worse) performance under this setting.
