### ISSUE TITLE
A confusion about the algorithm

### ISSUE THREAD

**Issue by hhhzzj** [cihangxie/DI-2-FGSM#4]
Hi, thanks for your great work. I am so interested in your work and i have a confusion about the algorithm.  The output of the transformation is resized to [330,330,3], while the original image is [299,299,3]. 
Are the input images(clean image) of the experiments all resized to [330,330,3]?
If resized, what is the resize method applied to clean image?
Thank you so much for answering!!!

**Comment by cihangxie** [comment]
Thanks for your interest in this work.

The resize function is here: https://github.com/cihangxie/DI-2-FGSM/blob/master/attack.py#L155

The resize process is embedded as a layer in the whole algorithms, so the generated adversarial examples are still of the size 299x299x3
