### ISSUE TITLE
Attack an ensemble of networks

### ISSUE THREAD

**Issue by LQNew** [cihangxie/DI-2-FGSM#5]
Hi, thx for your sharing. I notice that in your CVPR-19 paper "Improving transferbility of Adversarial examples with input diversity", your work contains attacking an ensemble of networks, but in your released code, I haven't found the corresponding code, can you release it?

**Comment by cihangxie** [comment]
Thanks for your interest in our work.

You can find the ensemble template in this repo https://github.com/dongyp13/Non-Targeted-Adversarial-Attacks/blob/master/attack_iter.py
