### ISSUE TITLE
Problems in code usage

### ISSUE THREAD

**Issue by Amarantine1** [cihangxie/DI-2-FGSM#7]
Hello, how to use this code? I've just been in the research field. I don't know how to use your code very well. What should I pay attention to when using this code? For example, what format should I initialize the parameters in attack.py, or can I have complete source code for reference? I'm in a hurry to study and use it. I hope you can help me solve this problem and reply to me as soon as possible. Sorry to disturb you, thank you.

**Comment by cihangxie** [comment]
If you are new to this research field, I would recommend you to try the tutorial at cleverhans (https://github.com/tensorflow/cleverhans/tree/master/tutorials) first for getting familiar with adversarial attacks.
