### ISSUE TITLE
Confusion on FGSM success rates when attack inc-v3.

### ISSUE THREAD

**Issue by Magallan1229** [cihangxie/DI-2-FGSM#8]
In table1 of this paper, FGSM has success rate of 64.6% on inc-v3 with maximum perturbation 15. However, in table2 of another paper MITIGATING ADVERSARIAL EFFECTS THROUGH RANDOMIZATION, success rates of FGSM on inc-v3 with different perturbations are 66.8%/68.9%/67.0%(perturbation 2/5/10 respectively). If I read you right, both these two work use 5000 random images of imagenet valset and use inc-v3 as source and target model ,so why FGSM with the largest perturbation has the lowest success rate?

**Comment by cihangxie** [comment]
Yes, FGSM with too large perturbations will result in a less effective attack. This is also observed in other papers, like adversarial machine learning at scale (https://arxiv.org/pdf/1611.01236.pdf, Table 1). The explanation there is the linearity assumption of deep networks only holds for small pixel changes.

**Comment by Magallan1229** [comment]
I see. Thank you for your reply.
